import type { AIAgentProps } from '@sendbird/ai-agent-messenger-react';

export const customStringSet: AIAgentProps['stringSet'] = {
  MESSAGE_INPUT__PLACE_HOLDER: 'Ask a question',
  MESSAGE_INPUT__PLACE_HOLDER__DISABLED: 'Chat is unavailable in this channel',
  MESSAGE_INPUT__PLACE_HOLDER__WAIT_AI_AGENT_RESPONSE: "Waiting for the agent's reply...",
  UNKNOWN__UNKNOWN_MESSAGE_TYPE: '(Unknown message type)',
  POWERED_BY: 'Powered by',
  CSAT_TITLE_UNSUBMITTED: 'Your feedback matters to us',
  CSAT_TITLE_SUBMITTED: 'Successfully submitted!',
  CSAT_CRE_TITLE: 'Was your issue resolved?',
  CSAT_CRE_SOLVED: 'Yes, thank you! 👍',
  CSAT_CRE_NOT_SOLVED: "No, that didn't help.",
  CSAT_REASON_PLACEHOLDER: 'Share your feedback',
  CSAT_RATING_TITLE: 'How would you rate your experience?',
  CSAT_SUBMIT_LABEL: 'Submit',
  CSAT_SUBMISSION_EXPIRED: "We're sorry, the survey period has ended.",
  DATE_FORMAT__JUST_NOW: 'Just now',
  DATE_FORMAT__MINUTES_AGO: (minutes) => `${minutes} minutes ago`,
  DATE_FORMAT__HOURS_AGO: (hours) => `${hours} hours ago`,
  DATE_FORMAT__DATE_SHORT: 'MM/dd/yyyy',
  DATE_FORMAT__MESSAGE_LIST__DATE_SEPARATOR: 'MMMM dd, yyyy',
  DATE_FORMAT__MESSAGE_TIMESTAMP: 'p',
  CONVERSATION_LIST__HEADER_TITLE: 'Conversations',
  CONVERSATION_LIST__ENDED: 'Ended',
  CONVERSATION_LIST__NO_CONVERSATIONS: 'No conversations yet',
  TALK_TO_AGENT: 'Talk to agent',
  CITATION_SOURCE_TITLE: 'Source',
  FORM_PLACEHOLDER: 'Please fill out the form to move forward.',
  FORM_VALIDATION_REQUIRED: 'This question is required',
  OPTIONAL: 'optional',
  PLACE_HOLDER__NO_MESSAGES: 'No messages',
  RETRY: 'Retry',
  FAILED_MESSAGE_RESEND: 'Retry',
  FAILED_MESSAGE_REMOVE: 'Remove',
  FILE_UPLOAD_NO_SUPPORTED_FILES: 'No supported file types available.',
  FEEDBACK_TITLE: 'Submit feedback',
  FEEDBACK_GOOD: 'Good',
  FEEDBACK_BAD: 'Bad',
  FEEDBACK_COMMENT_LABEL: 'Comment (optional)',
  FEEDBACK_COMMENT_PLACEHOLDER: 'Leave a comment',
  FEEDBACK_CANCEL: 'Cancel',
  FEEDBACK_SUBMIT: 'Submit',
  FEEDBACK_SAVE: 'Save',
  FEEDBACK_EDIT: 'Edit feedback',
  FEEDBACK_REMOVE: 'Remove feedback',

  HEADER_BUTTON__AGENT_HANDOFF: 'Connect with an agent',
  MESSAGE_INPUT__PLACE_HOLDER__SUGGESTED_REPLIES: 'Select an option to continue',
  BUTTON__CANCEL: 'Cancel',
  BUTTON__SUBMIT: 'Submit',
  SUBMITTED: 'Submitted',
  TRY_AGAIN: 'Please try again.',
  FILE_UPLOAD_NOTIFICATION__COUNT_LIMIT: "You can't upload more than one image",
  FILE_UPLOAD_NOTIFICATION__SIZE_LIMIT: 'The maximum size per file is %d MB.',
  FILE_VIEWER__UNSUPPORT: 'Unsupported message',
  CSAT5_RATING_SCORE_1: 'Terrible',
  CSAT5_RATING_SCORE_2: 'Bad',
  CSAT5_RATING_SCORE_3: 'Okay',
  CSAT5_RATING_SCORE_4: 'Good',
  CSAT5_RATING_SCORE_5: 'Great',
  FORM_UNAVAILABLE: 'Form is no longer available.',
  FORM_NOT_SUPPORTED: 'This form is not supported in the current version.',
  FORM_VALIDATION_MIN_LENGTH: (minLength) => `Minimum ${minLength} characters required`,
  FORM_VALIDATION_MAX_LENGTH: (maxLength) => `Maximum ${maxLength} characters allowed`,
  FORM_VALIDATION_MIN: (minValue) => `Minimum value is ${minValue}`,
  FORM_VALIDATION_MAX: (maxValue) => `Maximum value is ${maxValue}`,
  FORM_VALIDATION_MIN_SELECT: (minSelect) => `Select at least ${minSelect} options`,
  FORM_VALIDATION_MAX_SELECT: (maxSelect) => `Select at most ${maxSelect} options`,
  FORM_VALIDATION_REGEX_FAILED: 'Invalid format',
};
